### PR TITLE
Added project specific example for filetype mapping

### PR DESCRIPTION
**Pull request by WoLpH**

### CODE REVIEW

**Comment by benjifisher** [comment]
What is the use case for this?  That is, why do you have ansible files that are not recognized by the existing rules?

I think this suggestion only works if the current working directory when you start vim is the project directory.

I do not think this is needed often enough to warrant including in the README.  It might be more appropriate for `doc/ansible.txt`.  First I would want

- a clearer description of what goes in the user's vimrc file and what goes in the "project vimrc"
- fix the typo `fielsfiles`
- a more explicit example than `your*.yml`

Again, even if you do all that, you still have to convince me that this is a good idea.  I need a good reason to recommend `:set exrc nosecure`.

**Comment by WoLpH** [comment]
Something went seriously wrong here it seems... not sure where the `fielsfiles` and `your*.yml` came from but that shouldn't look like that and I'm very sure I didn't type it like that. Perhaps some drag/drop issue... :)

The use case is indeed non-recoginized ansible files, perhaps there's a better fix for that but this still seemed useful info to me.

One of the files I have over here that isn't recognized: `provisioning/_playbooks/add_psql_nginx_restart_cron.yml`
Contents:
```yaml
# Adds cron to restart PostgreSQL and NginX 2 minutes after reboot.
#
# On zandmotor-libprod occures a problem where network mounts are not ready when
# PostgreSQL starts. PostgreSQL has the database stored on that mount.
# NginX stores upload caching on /data.

- hosts: all
  connection: ssh
  tasks:
    - name: copy crontab files for nginx and postgres
      sudo: yes
      copy: src=files/cron.d/{{item}} dest=/etc/cron.d/{{item}} mode=0600
            owner=root group=root
      with_items:
        - nginx_restart
        - postgresql_restart
```

**Comment by benjifisher** [comment]
I think there are several simpler solutions available.  For example,

1. Add a modeline (as described under [Detection](https://github.com/chase/vim-ansible-yaml#detection) in the current README).
2. `mkdir provisioning/_playbooks/roles`
3. Add `au BufNewFile,BufRead */_playbooks/*.yml set filetype=ansible` to your vimrc file (usually `~/.vimrc`).

I have not tested these, so they may need some tweaking before they actually work.

**Comment by WoLpH** [comment]
Ok, in that case I'll go for one of the alternative options :)

1. Seems a bit useless, adding that to every file is just an ugly solution imho
2. That would solve it, although I would have to add a dummy file to the roles dir since `git` doesn't like empty dirs that much.
3. Should do the trick but requires me to do that on all machines, will happen eventually of course but faster is better :)

**Pull request closed without merging**
