### PR TITLE
set filetype as ansible AND YAML

### PR DESCRIPTION
**Pull request by erikzaadi**
To enable syntax checkers in syntastic

### CODE REVIEW

**Comment by rbowlby** [comment]
+1 Merge baby merge!!!

**Comment by codeinabox** [comment]
LGTM but which file type takes precedence for syntax highlighting, ftplugin etc?

**Comment by erikzaadi** [comment]
@codeinabox AFAIK the first

**Comment by codeinabox** [comment]
Should be easy to test, set different shiftwidth for both and see which one takes priority

**Comment by erikzaadi** [comment]
Yapp, the first, tested

**Comment by codeinabox** [comment]
Thank you for the PR, testing and patience

**Comment by erikzaadi** [comment]
Thank you!

**Pull request merged**
