### PR TITLE
README.md `.yml` or '.yaml'

### PR DESCRIPTION
**Pull request by gundalow**
Support `.yml` or '.yaml'

[Review on Reviewable](https://reviewable.io/reviews/chase/vim-ansible-yaml/50)

### CODE REVIEW

**Comment by codeinabox** [comment]
Thank you for the PR would read more naturally if written "The extensions are .." but happy to merge as is

**Comment by gundalow** [comment]
Good spot

**Comment by gundalow** [comment]
Fixed, ready to merge :)

**Comment by codeinabox** [comment]
Thank you

**Pull request merged**
